apiVersion: v1
kind: Service
metadata:
  name: milan
  labels:
    app: milan
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: milan

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milan
spec:
  replicas: 1
  selector:
    matchLabels:        
      run: milan
  template:
    metadata:
      labels:
        run: milan
    spec:
      containers:
      - name: milan
        image: milanevet/milan:latest
          # milanevet/milan:latest
        ports:
        - containerPort: 80



        # milanevet/intimacyng:v12