apiVersion: v1
kind: Service
metadata:
  name: bend
  labels:
    app: bend
spec:
  ports:
    - port: 70
      targetPort: 70
      protocol: TCP
      name: http
  selector:
    app: bend

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bend
spec:
  replicas: 1
  selector:
    matchLabels:        
      run: bend
  template:
    metadata:
      labels:
        run: bend
    spec:
      containers:
      - name: bend
        image: bendevet/milan:latest
        ports:
        - containerPort: 70



        # bendevet/intimacyng:v12