apiVersion: v1
kind: Service
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  ports:
    - port: 90
      targetPort: 90
  selector:
    app: hello-kenzan
    tier: hello-kenzan
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  selector:
    matchLabels:
      app: hello-kenzan
      tier: hello-kenzan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-kenzan
        tier: hello-kenzan
    spec:
      containers:
      - image: bendevet/milan:latest
        name: hello-kenzan
        ports:
        - containerPort: 90
          name: hello-kenzan